# Generated by Django 2.1.15 on 2024-06-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diabetes_diagnosis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
    ]
